# Generated by Django 5.2.3 on 2025-06-21 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="岗位名称")),
                ("company", models.CharField(max_length=100, verbose_name="企业名称")),
                ("city", models.CharField(max_length=50, verbose_name="工作地点")),
                (
                    "salary",
                    models.CharField(blank=True, max_length=50, verbose_name="薪资"),
                ),
                (
                    "work_experience",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="工作年限"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="学历要求"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="语言要求"
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(blank=True, verbose_name="岗位职责"),
                ),
                ("requirements", models.TextField(blank=True, verbose_name="岗位要求")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "岗位",
                "verbose_name_plural": "岗位",
            },
        ),
        migrations.CreateModel(
            name="JobOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="jobs.jobposition",
                        verbose_name="岗位",
                    ),
                ),
            ],
            options={
                "verbose_name": "岗位负责人",
                "verbose_name_plural": "岗位负责人",
                "unique_together": {("job", "user", "start_time")},
            },
        ),
    ]
