version: '3.8'

services:
  django:
    build: .
    container_name: lieying-django
    command: >
      gunicorn lieying.wsgi:application
      --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=lieying.settings
    networks:
      - lieying-net
    volumes:
      - .:/app
    restart: always

  mysql:
    image: mysql:8.0
    container_name: lieying-mysql
    ports:
      - "7790:3306"
    environment:
      MYSQL_DATABASE: lieying
      MYSQL_USER: lieying
      MYSQL_PASSWORD: lieying
      MYSQL_ROOT_PASSWORD: lieying
    volumes:
      - mysql-data:/var/lib/mysql
      - ./lieying.sql:/docker-entrypoint-initdb.d/lieying.sql:ro
    networks:
      - lieying-net
    restart: always

  redis:
    image: redis:7
    container_name: lieying-redis
    ports:
      - "7791:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - lieying-net
    restart: always

networks:
  lieying-net:
    driver: bridge

volumes:
  mysql-data:
