# Generated by Django 5.2.3 on 2025-06-21 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "resume_id",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="简历编号",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(verbose_name="版本号")),
                ("name", models.CharField(max_length=10, verbose_name="姓名")),
                ("status", models.CharField(max_length=10, verbose_name="状态")),
                ("personal_info", models.TextField(verbose_name="个人信息")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="电话号码"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                (
                    "expected_positions",
                    models.JSONField(blank=True, default=list, verbose_name="期望岗位"),
                ),
                (
                    "education",
                    models.JSONField(blank=True, default=list, verbose_name="教育经历"),
                ),
                ("certificates", models.TextField(blank=True, verbose_name="证书")),
                (
                    "skills",
                    models.JSONField(blank=True, default=list, verbose_name="技能"),
                ),
                (
                    "self_evaluation",
                    models.TextField(blank=True, verbose_name="自我评价"),
                ),
                (
                    "project_experiences",
                    models.JSONField(blank=True, default=list, verbose_name="项目经历"),
                ),
                (
                    "working_experiences",
                    models.JSONField(blank=True, default=list, verbose_name="工作经历"),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[("面试中", "面试中"), ("匹配中", "匹配中")],
                        max_length=20,
                        verbose_name="当前状态",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="resumes.resume",
                        verbose_name="所属简历",
                    ),
                ),
            ],
            options={
                "verbose_name": "简历版本",
                "verbose_name_plural": "简历版本",
                "ordering": ["-version_number"],
                "unique_together": {("resume", "version_number")},
            },
        ),
        migrations.AddField(
            model_name="resume",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="resumes.resumeversion",
                verbose_name="当前版本",
            ),
        ),
    ]
