# Generated by Django 5.2.3 on 2025-06-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="current_version",
        ),
        migrations.AlterModelOptions(
            name="resume",
            options={"verbose_name": "简历", "verbose_name_plural": "简历"},
        ),
        migrations.AddField(
            model_name="resume",
            name="certificates",
            field=models.TextField(blank=True, verbose_name="证书"),
        ),
        migrations.AddField(
            model_name="resume",
            name="current_status",
            field=models.CharField(
                choices=[("面试中", "面试中"), ("匹配中", "匹配中")],
                default="匹配中",
                max_length=20,
                verbose_name="当前状态",
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="education",
            field=models.JSONField(blank=True, default=list, verbose_name="教育经历"),
        ),
        migrations.AddField(
            model_name="resume",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
        ),
        migrations.AddField(
            model_name="resume",
            name="expected_positions",
            field=models.JSONField(blank=True, default=list, verbose_name="期望岗位"),
        ),
        migrations.AddField(
            model_name="resume",
            name="name",
            field=models.CharField(default="", max_length=10, verbose_name="姓名"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="personal_info",
            field=models.TextField(default="", verbose_name="个人信息"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="phone",
            field=models.CharField(blank=True, max_length=11, verbose_name="电话号码"),
        ),
        migrations.AddField(
            model_name="resume",
            name="project_experiences",
            field=models.JSONField(blank=True, default=list, verbose_name="项目经历"),
        ),
        migrations.AddField(
            model_name="resume",
            name="self_evaluation",
            field=models.TextField(blank=True, verbose_name="自我评价"),
        ),
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.JSONField(blank=True, default=list, verbose_name="技能"),
        ),
        migrations.AddField(
            model_name="resume",
            name="status",
            field=models.CharField(default="", max_length=10, verbose_name="状态"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="标签"),
        ),
        migrations.AddField(
            model_name="resume",
            name="working_experiences",
            field=models.JSONField(blank=True, default=list, verbose_name="工作经历"),
        ),
        migrations.DeleteModel(
            name="ResumeVersion",
        ),
    ]
