# Generated by Django 5.2.3 on 2025-06-23 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_uploadrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadrecord",
            name="parse_status",
            field=models.CharField(
                choices=[("success", "解析成功"), ("fail", "解析失败")],
                default="fail",
                max_length=10,
                verbose_name="解析状态",
            ),
        ),
        migrations.AddField(
            model_name="uploadrecord",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resumes.resume",
                verbose_name="关联简历",
            ),
        ),
        migrations.AlterField(
            model_name="uploadrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
