# Generated by Django 4.2.5 on 2025-06-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_uploadrecord_parse_status_uploadrecord_resume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadrecord',
            options={'verbose_name': '简历上传记录', 'verbose_name_plural': '简历上传记录'},
        ),
        migrations.AlterField(
            model_name='resume',
            name='personal_info',
            field=models.TextField(blank=True, verbose_name='个人信息'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('离职，正在找工作', '离职，正在找工作'), ('在职，急寻新工作', '在职，急寻新工作'), ('在职，看看新机会', '在职，看看新机会'), ('在职，暂无跳槽打算', '在职，暂无跳槽打算')], default='在职，看看新机会', max_length=20, verbose_name='状态'),
        ),
    ]
