# Generated by Django 5.2.3 on 2025-06-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_uploadrecord_parse_status_uploadrecord_resume_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadrecord",
            options={
                "verbose_name": "简历上传记录",
                "verbose_name_plural": "简历上传记录",
            },
        ),
    ]
